CREATE COLLECTION EVENT_PUBLICATION IF NOT EXISTS;

CREATE INDEX IF NOT EXISTS EVENT_PUBLICATION_BY_ID_AND_COMPLETION_DATE_ORDER_BY_PUBLICATION_DATE_ASC_IDX ON EVENT_PUBLICATION (META().id, completionDate, publicationDate ASC);
CREATE INDEX IF NOT EXISTS EVENT_PUBLICATION_BY_ID_AND_STATUS_IDX ON EVENT_PUBLICATION (META().id, status);
CREATE INDEX IF NOT EXISTS EVENT_PUBLICATION_BY_STATUS_IDX ON EVENT_PUBLICATION (status);
CREATE INDEX IF NOT EXISTS EVENT_PUBLICATION_BY_PUBLICATION_DATE_IDX ON EVENT_PUBLICATION (publicationDate INCLUDE MISSING);
CREATE INDEX IF NOT EXISTS EVENT_PUBLICATION_BY_COMPLETION_DATE_IDX ON EVENT_PUBLICATION (completionDate);
CREATE INDEX IF NOT EXISTS EVENT_PUBLICATION_BY_COMPLETION_DATE_AND_LISTENER_ID_IDX ON EVENT_PUBLICATION (listenerId, completionDate IS MISSING) WHERE completionDate IS MISSING;
CREATE INDEX IF NOT EXISTS EVENT_PUBLICATION_BY_PUBLICATION_DATE_AND_STATUS_IDX ON EVENT_PUBLICATION (status, publicationDate);