[[fundamentals]]
= Fundamentals

Spring Modulith supports developers implementing logical modules in Spring Boot applications.
I allows them to apply structural validation, document the module arrangement, run integration tests for individual modules, observe the modules interaction at runtime and generally implement module interaction in a loosely-coupled way.
This section will discuss the fundamental concepts that developers need to understand before diving into the technical support.

[[fundamentals.modules]]
== Application modules

In a Spring Boot application, an application module is a unit of functionality that consists of the following parts:

* An API exposed to other modules implemented by Spring bean instances and application events published by the module, usually referred to as _provided interface_.
* Internal implementation components that are not supposed to be accessed by other modules.
* References to API exposed by other modules in the form of Spring bean dependencies, application events listened to and configuration properties exposed.

Spring Moduliths provides different ways of expressing modules, primarily differing in the level of complexity involved in the overall arrangement.
This allows developers to start simple and naturally move to more sophisticated means as and if needed.

[[fundamentals.modules.simple]]
=== Simple Application Modules

The application's main package is the one that the main application class resides in.
The class, that is annotated with `@SpringBootApplication` and usually contains the `main(…)` method used to run it.
By default, each direct sub-package of the main package is considered an application module package.

If this package does not contain any sub-packages, it is considered a simple one.
It allows to hide code inside it by using Java's package scope to hide types from being referred to by code residing in other packages and thus not subject for dependency injection into those.
Thus, naturally, the module's API consists of all public types in the package.

Let us have a look at an example arrangement (icon:plus-circle[] denotes a public type, icon:minus-circle[] a package protected one).

[source, subs="macros"]
----
icon:cubes[] Example
└─ icon:folder[] src/main/java
   ├─ icon:cube[] example                      <1>
   |  └─ icon:plus-circle[] Application.java
   └─ icon:cube[] example.inventory            <2>
      ├─ icon:plus-circle[] InventoryManagement.java
      └─ icon:minus-circle[] SomethingInventoryInternal.java
----
<1> The application's main package `example`.
<2> An application module package `inventory`.

[[fundamentals.modules.advanced]]
=== Advanced Application Modules

If an application module package contains sub-packages, types in those might need to be made public so that it can be referred to from code of the very same module.

[source, subs="macros"]
----
icon:cubes[] Example
└─ icon:folder[] src/main/java
   ├─ icon:cube[] example
   |  └─ icon:plus-circle[] Application.java
   ├─ icon:cube[] example.inventory
   |  ├─ icon:plus-circle[] InventoryManagement.java
   |  └─ icon:minus-circle[] SomethingInventoryInternal.java
   ├─ icon:cube[] example.order
   |  └─ icon:plus-circle[] OrderManagement.java
   └─ icon:cube[] example.order.internal
      └─ icon:plus-circle[] SomethingOrderInternal.java
----

In such an arrangement, the `order` package is considered an API package.
Code from other application modules is allowed to refer to types within that.
`order.internal`, just as any other sub-package of the application module base package are considered _internal_ ones.
Code within those must not be referred to from other modules.
Note, how `SomethingOrderInternal` is a public type, likely because `OrderManagement` depends on it.
This unfortunately means, that it can also be referred to from other packages such as the `inventory` one.

[[fundamentals.modules.application-modules]]
=== The `ApplicationModules` Type

Spring Moduliths allows to inspect a codebase to derive an application module model based on the given arrangement and optional configuration.
The `spring-modulith-core` artifact contains `ApplicationModules` that can be pointed to a Spring Boot application class:

[source, java]
----
var modules = ApplicationModules.of(Application.class);
----

To get an impression about what the analyzed arrangement looks like, we can just write the individual modules contained in the overall model to the console:

[source, java]
----
modules.forEach(System.out::println);
----

[source]
----
## example.inventory ##
> Logical name: inventory
> Base package: example.inventory
> Spring beans:
  + ….InventoryManagement
  o ….SomeInternalComponent

## example.order ##
> Logical name: order
> Base package: example.order
> Spring beans:
  + ….OrderManagement
  + ….internal.SomeInternalComponent
----

Note, how each module is listed and the contained Spring components are identified and the respective visibility is rendered, too.

[[fundamentals.modules.named-interface]]
=== Named Interfaces
