antora:
  extensions:
    - require: '@springio/antora-extensions'
      root_component_name: 'modulith'
site:
  title: Spring Modulith
  url: https://docs.spring.io/spring-modulith/reference/
content:
  sources:
    - url: ./../../..
      branches: HEAD
      start_path: src/docs/antora
      worktrees: true
asciidoc:
  attributes:
    page-pagination: ''
    hide-uri-scheme: '@'
    tabs-sync-option: '@'
    chomp: 'all'
    kroki-fetch-diagram: true
  extensions:
    - asciidoctor-kroki
    - '@asciidoctor/tabs'
    - '@springio/asciidoctor-extensions'
  sourcemap: true
urls:
  latest_version_segment: ''
runtime:
  log:
    failure_level: warn
    format: pretty
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/v0.4.17/ui-bundle.zip
