CREATE COLLECTION EVENT_PUBLICATION_ARCHIVE IF NOT EXISTS;

CREATE INDEX IF NOT EXISTS EVENT_PUBLICATION_ARCHIVE_BY_COMPLETION_DATE_IDX ON EVENT_PUBLICATION_ARCHIVE (completionDate);
CREATE INDEX IF NOT EXISTS EVENT_PUBLICATION_ARCHIVE_BY_STATUS_IDX ON EVENT_PUBLICATION_ARCHIVE (status);
CREATE INDEX IF NOT EXISTS EVENT_PUBLICATION_ARCHIVE_BY_ID_AND_STATUS_IDX ON EVENT_PUBLICATION_ARCHIVE (META().id, status);

