spring.modulith.events.externalization.mode=outbox
logging.level.org.springframework.jdbc=debug
logging.level.org.springframework.modulith=debug

# Namastack
logging.level.io.namastack=debug
namastack.outbox.instance.graceful-shutdown-timeout-seconds=0

# JobRunr
logging.level.org.jobrunr=debug
jobrunr.dashboard.enabled=true
jobrunr.background-job-server.enabled=true
jobrunr.background-job-server.poll-interval-in-seconds=5
