CREATE TABLE IF NOT EXISTS EVENT_PUBLICATION
(
  ID               VARCHAR(36) NOT NULL,
  LISTENER_ID      VARCHAR(512) NOT NULL,
  EVENT_TYPE       VARCHAR(512) NOT NULL,
  SERIALIZED_EVENT VARCHAR(4000) NOT NULL,
  PUBLICATION_DATE TIMESTAMP(6) NOT NULL,
  COMPLETION_DATE  TIMESTAMP(6) DEFAULT NULL NULL,
  PRIMARY KEY (ID),
  INDEX EVENT_PUBLICATION_BY_COMPLETION_DATE_IDX (COMPLETION_DATE)
);
CREATE TABLE IF NOT EXISTS EVENT_FAILED_ATTEMPT_INFO
(
  EVENT_ID               VARCHAR(36) NOT NULL,
  FAILED_DATE  TIMESTAMP(6) NOT NULL,
  SERIALIZED_REASON VARCHAR(4000) NOT NULL,
  REASON_TYPE       VARCHAR(512) NOT NULL,
    CONSTRAINT FK_FAILED_EVENT_INFO_EVENT
        FOREIGN KEY (EVENT_ID)
        REFERENCES EVENT_PUBLICATION(ID)
        ON DELETE CASCADE

);