CREATE TABLE IF NOT EXISTS EVENT_PUBLICATION
(
  ID               UUID NOT NULL,
  COMPLETION_DATE  TIMESTAMP(9) WITH TIME ZONE,
  EVENT_TYPE       VARCHAR(512) NOT NULL,
  LISTENER_ID      VARCHAR(512) NOT NULL,
  PUBLICATION_DATE TIMESTAMP(9) WITH TIME ZONE NOT NULL,
  SERIALIZED_EVENT VARCHAR(4000) NOT NULL,
  PRIMARY KEY (ID)
);
CREATE INDEX IF NOT EXISTS EVENT_PUBLICATION_BY_LISTENER_ID_AND_SERIALIZED_EVENT_IDX ON EVENT_PUBLICATION (LISTENER_ID, SERIALIZED_EVENT);
CREATE INDEX IF NOT EXISTS EVENT_PUBLICATION_BY_COMPLETION_DATE_IDX ON EVENT_PUBLICATION (COMPLETION_DATE);
CREATE TABLE IF NOT EXISTS EVENT_FAILED_EVENT_INFO
(
  EVENT_ID               UUID NOT NULL,
  FAILED_DATE  TIMESTAMP(9) WITH TIME ZONE,
  SERIALIZED_REASON VARCHAR(4000) NOT NULL,
  REASON_TYPE       VARCHAR(512) NOT NULL,
    CONSTRAINT FK_FAILED_EVENT_INFO_EVENT
        FOREIGN KEY (EVENT_ID)
        REFERENCES EVENT_PUBLICATION(ID)
        ON DELETE CASCADE

);
